export const FETCH_DOLARTODAY_DATA = 'FETCH_DOLARTODAY_DATA';
export const FETCH_BITCOIN_HISTORY_DATA = 'FETCH_BITCOIN_HISTORY_DATA';
export const FETCH_ETHERUM_HISTORY_DATA = 'FETCH_ETHERUM_HISTORY_DATA';
export const FETCH_BITCOIN_CURRENT_DATA = 'FETCH_BITCOIN_CURRENT_DATA';
export const FETCH_ETHEREUM_CURRENT_DATA = 'FETCH_ETHEREUM_CURRENT_DATA';